name: Node.js Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test -- --headless
      - run: npm run build
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "dist"
          path: dist

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download dist result from job build
        uses: actions/download-artifact@v1
        with:
          name: "dist"
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@dlr-eoc"
      - run: npm ci
      ### for each module in dist publish frontend-libraries to registry
      - run: npm run setVersionsInBuild
      - run: find ./dist -mindepth 1 -maxdepth 1 -type d -exec bash -c "cd '{}' && node ../../scripts/library/update-package-for-github.js" \;
      - run: find ./dist -mindepth 1 -maxdepth 1 -type d -exec bash -c "cd '{}' && npm publish" \;
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
